#
# The name of your game. Please make sure
# it matches the repository name
#
project_name: mage

#
# A unique ID provided by
# server operations
#
# ** DO NOT PICK A RANDOM ID **
#
id: 17

#
# The roles your game will need.
#
# By default, the following
# roles are automatically included
#
#    - common
#    - nodejs
#    - nginx
#    - loadbalancer
#    - web
#
# To see what roles are currently
# available for install:
#
# ```bash
# ls ${AERISCLOUD_PATH}/ansible/roles
# ```
#
services:
 - couchbase
 - dynamodb
 - elasticsearch
 - redis
 - shokoti
 - zookeeper
 - xtradb
 - collector

# There is no AerisCloud playbook roles for these services on centos7, temporary disable it until a patch is done.
#  - dynamodb
#  - elasticsearch
#  - shokoti

#
# The infrastructures you will
# deploy to in production.
#
# To see what environments are available:
#
# ```bash
# aeriscloud vagrant status
# ```
#
# Each infrastructure can be configured:
#
#   image: the base image you wish to use (e.g. what OS, what version)
#   cpu: how many CPU do you want to start this machine with?
#   ram: how much RAM do you want to start this machine with?
#
boxes:
  - name: centos
    basebox: base/centos-6.6
    cpu: 1
    ram: 2048
basebox_url: http://boxes-aeriscloud.wizcorp.jp/meta

#
# Activate debugging of the provisioning process
#
# See http://docs.vagrantup.com/v2/provisioning/ansible.html
#
# For more details on how to configure this variable
#
# debug: "vvv"

#
# Extra configruation variables
#
# These variables will be passed down to ansible's provisioning
# script. Anything configurable in the roles can be configured for
# development here
#
timezone: Asia/Tokyo
node_version: v0.10.35
xtradb_version: "56"
