developmentMode: true

archivist:
    vaults:
        memory:
            type: memory
    listOrder:
        - memory
    readOrder:
        - memory
    writeOrder:
        - client
        - memory
